const GET_COUNTRIES_REQUEST = '@@country/GET_COUNTRIES_REQUEST';
const GET_COUNTRIES_SUCCESS = '@@country/GET_COUNTRIES_SUCCESS';

export default {
  GET_COUNTRIES_REQUEST,
  GET_COUNTRIES_SUCCESS,
};
